config/routes.rb
Rails.application.routes.draw do



  root "movies#index"

  resources :genres

  resource :session, only: [:new, :create, :destroy]

  resources :movies do
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end

  resources :users

  get "signup" => "users#new"
  get "signin" => "sessions#new"

  get "movies/filter/:filter" => "movies#index", as: :filtered_movies

end

app/models/genre.rb
class Genre < ApplicationRecord

  before_save :set_slug

  has_many :characterizations, dependent: :destroy
  has_many :movies, through: :characterizations

  validates :name, presence: true, uniqueness: true

  def to_param
    slug
  end


  private

  def set_slug
    self.slug = name.parameterize
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  before_action :require_signin, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]
  before_action :set_genre, except: [:index, :new, :create]

  def index
    @genres = Genre.all
  end

  def show
  end

  def edit
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to @genre, notice: "Genre successfully created!"
    else
      render :new
    end
  end

  def update
    if @genre.update(genre_params)
      redirect_to @genre, notice: "Genre successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @genre.destroy
    redirect_to genres_url, alert: "Genre successfully deleted!"
  end


  private

  def set_genre
    @genre = Genre.find_by!(slug: params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with(model: genre, local: true) do |f| %>

  <%= render "shared/errors", object: genre %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.submit %>

<% end %>

app/views/genres/edit.html.erb
<h2>Edit Genre</h2>

<%= render "form", genre: @genre %>

app/views/genres/index.html.erb
<h2>Genres</h2>

<aside>
  <ul>
    <% @genres.each do |genre| %>
      <li>
        <%= link_to genre.name, genre %>
      </li>
    <% end %>
  </ul>
</aside>

<% if current_user_admin? %>
  <section class="admin">
    <%= link_to "Add New Genre", new_genre_path, class: "button" %>
  </section>
<% end %>

app/views/genres/new.html.erb
<h2>Add a New Genre</h2>

<%= render "form", genre: @genre %>

app/views/genres/show.html.erb
<h2><%= @genre.name %> Movies</h2>

<aside>
  <ul>
    <% @genre.movies.each do |movie| %>
      <li>
        <%= link_to movie.title, movie %>
      </li>
    <% end %>
  </ul>
</aside>

<% if current_user_admin? %>
  <section class="admin">
    <%= link_to "Edit", edit_genre_path(@genre), class: "button" %>
    <%= link_to "Delete", genre_path(@genre), class: "button",
             method: :delete, data: { confirm: "Are you sure?" } %>
  </section>
<% end %>